### ISSUE TITLE
Add leaderboard endpoint

### ISSUE THREAD

**Issue by nishtahir** [nishtahir/hawthorn#23]
This should return the top 20 decks sorted by ELO which have played a game within the last 4 weeks.

**Comment by seanKenkeremath** [comment]
* And have played at least 5 games

**Comment by Kritarie** [comment]
For implementation, I think it doesn't necessarily need to be its own endpoint. I think the client should be able to simply query `host/decks`, pass query param to get X entries, sort by Y

**Comment by seanKenkeremath** [comment]
I agree for other query type stuff, but since we want to ensure the leaderboard is the exact same across all clients i think it would be worth ahving it's own endpoint to hide those implementation details. Even if it's just a pass through to the normal `/decks` call with some query params

**Comment by Kritarie** [comment]
hmm yeah I suppose in that case it's fine. Advantage here is that if we ever decide the leaderboard should include 25 entries instead of 20, clients don't have to update

**Comment by nishtahir** [comment]
So looks like the query params thing in rocket it a little weird right now. I'd like to revisit this when we have an actual need for it or when rocket 0.4 releases with the query params rewrite.
